import fs from 'fs';
import path from 'path';
import { app } from 'electron';

export class ObsidianExporter {
    public async exportToMarkdown(data: any) {
        const fileName = `AI-Audit-${Date.now()}.md`;
        const desktopPath = app.getPath('desktop');
        const filePath = path.join(desktopPath, fileName);

        const content = `---
type: audit
date: ${new Date().toISOString()}
---
# تقرير أداء النظام

- CPU: ${data.cpuUsage}%
- RAM: ${data.ramPercentage}%
- Security: Secure (Offline)

Generated by LocalAI Studio.`;

        fs.writeFileSync(filePath, content, 'utf8');
        return filePath;
    }
}