import fs from 'fs';
import path from 'path';
import { app } from 'electron';

export class ObsidianExporter {
    public async exportChat(session: { title: string, messages: any[] }, vaultPath?: string) {
        try {
            const fileName = `${session.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}-${Date.now()}.md`;
            const targetDir = vaultPath && fs.existsSync(vaultPath)
                ? vaultPath
                : path.join(app.getPath('userData'), 'obsidian_vault');

            if (!fs.existsSync(targetDir)) {
                fs.mkdirSync(targetDir, { recursive: true });
            }

            const filePath = path.join(targetDir, fileName);

            const content = `---
type: ai-chat
session: ${session.title}
date: ${new Date().toISOString()}
tags: [localai, insight-studio, documentation]
---
# ${session.title}

${session.messages.map((m: any) => `### [${m.sender === 'user' ? '👤 المستخدم' : '🤖 الذكاء الاصطناعي'}] - ${new Date(m.timestamp).toLocaleTimeString()}
${m.text}
`).join('\n---\n')}

---
*تولدت هذه الجلسة آلياً عبر LocalAI Insight Studio بصيغة Markdown متوافقة مع Obsidian.*`;

            fs.writeFileSync(filePath, content, 'utf8');
            return { success: true, filePath };
        } catch (error) {
            console.error('Failed to export to Obsidian:', error);
            return { success: false, error };
        }
    }

    public async exportAudit(data: any, vaultPath?: string) {
        const fileName = `AI-Audit-${Date.now()}.md`;
        const targetDir = vaultPath && fs.existsSync(vaultPath)
            ? vaultPath
            : path.join(app.getPath('userData'), 'obsidian_vault');

        if (!fs.existsSync(targetDir)) {
            fs.mkdirSync(targetDir, { recursive: true });
        }

        const filePath = path.join(targetDir, fileName);

        const content = `---
type: audit
date: ${new Date().toISOString()}
---
# تقرير أداء النظام

- **استهلاك المعالج:** ${data.cpuUsage}%
- **استهلاك الرام:** ${data.ramPercentage}%
- **حالة الأمان:** آمن (محلي بالكامل)

Generated by LocalAI Studio.`;

        fs.writeFileSync(filePath, content, 'utf8');
        return filePath;
    }
}